# Generated by Django 5.1.4 on 2025-01-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('lmp_date', models.DateField()),
                ('baby_birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
